include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

analyzer:
  exclude:
    - build/**

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    directives_ordering: true
    prefer_single_quotes: true
    require_trailing_commas: true
